name: test
on:
  issue_comment:
    types: [created]
    
jobs:
  build:
    if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, 'test this please')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Debug(check event object)
        run: |
          cat << OBJECT
          ${{ toJson(github) }}
          OBJECT
      - uses: octokit/request-action@v2.x
        id: get_pulls_approver
        with:
          route: GET /repos/{owner}/{repo}/pulls/{number}/reviews
          owner: octokit
          repo: request-action
          number: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo revews data: ${{ steps.get_latest_release.outputs.data }}"
