name: test
on:
  issue_comment:
    types: [created]
    
jobs:
  build:
    if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, 'test this please')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # Find the PR associated with this push, if there is one.
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
      - name: Debug(check event object)
        run: |
          cat << OBJECT
          ${{ toJson(github) }}
          OBJECT
          cat << OBJECT
          ${{ toJson(steps.findPr.outputs) }}
          OBJECT
