name: test
on:
  issue_comment:
    types: [created]
    
jobs:
  build:
    if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, 'test this please')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Debug(check event object)
        run: |
          cat << OBJECT
          ${{ toJson(github) }}
          OBJECT
      - name: get_reviews from comment
        id: get_reviews
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:repository/pulls/:pr_number/reviews
          repository: ${{ github.repository }}
          pr_number: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Debug(reviews)
        run: |
          cat << OBJECT
          ${{ toJson(steps.get_reviews.outputs.data) }}
          OBJECT
